include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unnecessary_const
    - unnecessary_new

    # Code quality
    - avoid_print
    - always_declare_return_types
    - avoid_unnecessary_containers
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - prefer_is_empty
    - prefer_is_not_empty
    - require_trailing_commas
    - unnecessary_brace_in_string_interps
    - use_key_in_widget_constructors

    # Error prevention
    - no_duplicate_case_values
    - valid_regexps
    - unnecessary_statements

analyzer:
  errors:
    # Treat missing returns as errors
    missing_return: error
    # Treat missing required parameters as errors
    missing_required_param: error
    # Allow TODO comments
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
