name: parachute
description: "Capture every moment effortlessly with our cross-platform voice recorder, designed for seamless background operation and crystal-clear audio."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  permission_handler: ^12.0.0
  record: ^6.1.2
  just_audio: ^0.9.42
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0
  http: ^1.2.0
  url_launcher: ^6.3.0
  file_picker: ^8.0.0+1
  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  # Omi Device Integration
  flutter_blue_plus: ^1.33.6
  flutter_local_notifications: ^17.0.0
  collection: ^1.18.0
  uuid: ^4.4.0
  # Audio codecs (for Omi device audio)
  opus_dart: ^3.0.1
  opus_flutter: ^3.0.3
  # Local Whisper transcription
  whisper_ggml: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  # Code generation for Riverpod
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/firmware/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
