name: parachute
description: "Capture every moment effortlessly with our cross-platform voice recorder, designed for seamless background operation and crystal-clear audio."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  permission_handler: ^12.0.0
  flutter_sound: ^9.0.0
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0
  speech_to_text: ^7.0.0
  http: ^1.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
